#!/usr/bin/env python3
"""Build a versioned, offline common-set catalog from Smogon monthly reports."""
import argparse
import json
import re
from pathlib import Path
from urllib.request import urlopen

ROOT = Path(__file__).resolve().parents[1]
SEPARATOR = "+----------------------------------------+"
STATS = ("hp", "at", "df", "sa", "sd", "sp")


def parse_movesets(text):
    result = {}
    for block in re.split(r"\+[-]+\+\s*\n\s*\+[-]+\+", text):
        sections = []
        for section in block.split(SEPARATOR):
            lines = [line.strip().strip("|").strip() for line in section.splitlines()]
            lines = [line for line in lines if line]
            if lines:
                sections.append(lines)
        if not sections:
            continue
        name = sections[0][0]
        groups = {section[0]: section[1:] for section in sections[1:]}

        def values(key):
            return [re.sub(r"\s+[\d.]+%$", "", line) for line in groups.get(key, [])
                    if not line.startswith("Other ")]

        spreads = values("Spreads")
        if not spreads:
            raise ValueError(f"Missing spread: {name}")
        nature, points = spreads[0].split(":")
        points = [int(point) for point in points.split("/")]
        if len(points) != 6 or any(point < 0 or point > 32 for point in points) or sum(points) > 66:
            raise ValueError(f"Invalid Champions SPs: {name}: {points}")
        abilities, items, moves = values("Abilities"), values("Items"), values("Moves")
        if not abilities or not items or not moves:
            raise ValueError(f"Incomplete set: {name}")
        result[name] = dict(ability=abilities[0], item="" if items[0] == "Nothing" else items[0],
                            nature=nature, sps=dict(zip(STATS, points)),
                            moves=[move for move in moves if move != "Nothing"][:4])
    return result


def build_catalog(usage, movesets, month, regulation):
    sets = parse_movesets(movesets)
    entries = []
    for line in usage.splitlines():
        match = re.match(r"\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([\d.]+)%", line)
        if not match:
            continue
        rank, pokemon, percentage = match.groups()
        if int(rank) > 125:
            break
        if pokemon not in sets:
            raise ValueError(f"Missing moveset for ranked Pokémon: {pokemon}")
        entries.append(dict(rank=int(rank), pokemon=pokemon, usage=float(percentage), **sets[pokemon]))
    if len(entries) != 125 or len({entry['pokemon'] for entry in entries}) != 125:
        raise ValueError("Expected 125 distinct ranked Pokémon")
    format_name = f"gen9championsvgc{month[:4]}reg{regulation.lower()}bo3-1760"
    root = f"https://www.smogon.com/stats/{month}"
    return dict(month=month, regulation=regulation.upper(), rating=1760,
                sources=[f"{root}/{format_name}.txt", f"{root}/moveset/{format_name}.txt"], sets=entries)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--month", required=True)
    parser.add_argument("--regulation", required=True, help="Regulation belonging to the report; never inferred from its month")
    parser.add_argument("--usage-file", type=Path)
    parser.add_argument("--movesets-file", type=Path)
    parser.add_argument("--output", type=Path, default=ROOT / "crates/spreadlab-web/assets/common-sets.js")
    args = parser.parse_args()
    if not re.fullmatch(r"\d{4}-(0[1-9]|1[0-2])", args.month) or not re.fullmatch(r"[a-zA-Z]+", args.regulation):
        parser.error("Expected YYYY-MM month and alphabetic regulation")
    root = f"https://www.smogon.com/stats/{args.month}"
    filename = f"gen9championsvgc{args.month[:4]}reg{args.regulation.lower()}bo3-1760.txt"

    def read(path, url):
        if path:
            return path.read_text()
        with urlopen(url, timeout=60) as response:
            return response.read().decode("utf-8")

    catalog = build_catalog(read(args.usage_file, f"{root}/{filename}"),
                            read(args.movesets_file, f"{root}/moveset/{filename}"),
                            args.month, args.regulation)
    # Validate everything before replacing the committed snapshot.
    content = "// Generated by tools/import-common-sets.py from Smogon monthly statistics.\n"
    content += "const COMMON_SETS = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"
    args.output.write_text(content)
    print(f"Wrote {len(catalog['sets'])} common sets to {args.output}")


if __name__ == "__main__":
    main()
